# Generated by Django 6.0 on 2026-01-02 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Image', models.FileField(upload_to='image')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, default=1.99, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('F', 'Fashion'), ('A', 'Accessories'), ('W', 'Wearables'), ('C', 'Computers')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
