# Generated by Django 6.0 on 2026-01-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default='This is product description'),
        ),
    ]
