name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image (debug)
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/e_com:latest .

    - name: Log in to Docker Hub (debug)
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image (debug)
      run: docker push ${{ secrets.DOCKER_USERNAME }}/e_com:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Use the root of the repo as the context
        push: true  # Push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/ecom:latest  # Use Docker Hub username and tag
        platforms: linux/amd64,linux/arm64  # Specify platforms to build for

